services:
  - type: web
    name: master-gateway
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TEMP_JWT_SECRET
        sync: false
      - key: REFRESH_JWT_SECRET
        sync: false
      - key: INTERNAL_API_KEY
        sync: false
      - key: SEED_ADMIN_EMAIL
        value: admin@example.com
      - key: SEED_ADMIN_PASSWORD
        sync: false
