sonar.projectKey=master-gateway
sonar.projectName=Master Gateway
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000

sonar.sources=backend/src,frontend/src
sonar.tests=backend/src,backend/test
sonar.test.inclusions=backend/src/**/*.spec.ts,backend/test/**/*.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,backend/prisma/migrations/**,frontend/dist/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
